### PR TITLE
Removed dev code.

### PR DESCRIPTION
**Pull request by iBalag**

### CODE REVIEW

**Comment by iBalag** [comment]
@nchursin Could you please approve these minor changes?

**Review by nchursin — APPROVED** [review]

**Comment by nchursin** [comment]
Seems like my review doesn't count - still unable to merge

**Comment by iBalag** [comment]
@nchursin I have invited you to this repository. It should fix the situation.

**Comment by nchursin** [comment]
@iBalag yup, that worked, thanks

**Pull request merged**
